### ISSUE TITLE
What about to include this to the main awesome list?

### ISSUE THREAD

**Issue by pravic** [onqtam/awesome-cmake#3]
Haven't found awesome-cmake in PR or Issues of https://github.com/sindresorhus/awesome.

**Comment by onqtam** [comment]
I'll submit it later - [here](https://github.com/sindresorhus/awesome/blob/master/create-list.md) it says to wait 20 days before submitting.

**Comment by onqtam** [comment]
the [PR](https://github.com/sindresorhus/awesome/pull/779)
