### ISSUE TITLE
Licensing informtion for osg-3rdparty-cmake

### ISSUE THREAD

**Issue by bjornblissing** [onqtam/awesome-cmake#9]
The osg-3rdparty-cmake uses a lot of licenses actually, since every dependency it builds have its own license. Hence all dependency specific build scripts must be considered as derivative works and thus must adhere to these licenses.

But the main script which holds everything together is written by me and is using the `unlicense`.
http://unlicense.org/

**Comment by onqtam** [comment]
Hmmm true - perhaps a ```[MIXED]``` label would be more appropriate than ```[NO LICENSE]```?

**Comment by bjornblissing** [comment]
Yes, that would probably be the most appropriate.
